name: Upload to PyPI

on:
  push:
    tags:
      - 'v*'  # Triggers only on version tags like v0.1.0

jobs:
  build-and-publish:
    name: Build and publish Python package to PyPI
    runs-on: ubuntu-latest

    permissions:
      id-token: write  # For OIDC (if PyPI supports in future)
      contents: read

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip build twine

    - name: Build package
      run: python -m build

    - name: Publish to PyPI
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
      run: |
        python -m twine upload dist/*
